# Generated by Django 2.2.3 on 2019-08-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_registration',
            name='image',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
