# Generated by Django 2.2.3 on 2019-09-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employee_personal_information_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_personal_information',
            name='image',
            field=models.FileField(default=None, upload_to='employees_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_personal_information',
            name='GENDER',
            field=models.CharField(max_length=30),
        ),
    ]
