# Generated by Django 2.2.3 on 2019-09-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190902_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Intermediate_Education',
            fields=[
                ('ID_NO', models.AutoField(primary_key=True, serialize=False)),
                ('Start_Date', models.CharField(max_length=30)),
                ('Completion_Date', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('Education_Institution', models.CharField(max_length=30)),
                ('Board_or_University', models.CharField(max_length=30)),
                ('Cousre_Type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_PG_Education',
            fields=[
                ('ID_NO', models.AutoField(primary_key=True, serialize=False)),
                ('Start_Date', models.CharField(max_length=30)),
                ('Completion_Date', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('Education_Institution', models.CharField(max_length=30)),
                ('Board_or_University', models.CharField(max_length=30)),
                ('Cousre_Type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_UG_Education',
            fields=[
                ('ID_NO', models.AutoField(primary_key=True, serialize=False)),
                ('Start_Date', models.CharField(max_length=30)),
                ('Completion_Date', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('Education_Institution', models.CharField(max_length=30)),
                ('Board_or_University', models.CharField(max_length=30)),
                ('Cousre_Type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_X_Education',
            fields=[
                ('ID_NO', models.AutoField(primary_key=True, serialize=False)),
                ('Start_Date', models.CharField(max_length=30)),
                ('Completion_Date', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('Education_Institution', models.CharField(max_length=30)),
                ('Board_or_University', models.CharField(max_length=30)),
                ('Cousre_Type', models.CharField(max_length=30)),
            ],
        ),
    ]
