# Generated by Django 2.2.3 on 2019-09-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190902_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_intermediate_education',
            name='BRANCH',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='employee_intermediate_education',
            name='PERCENTAGE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee_pg_education',
            name='BRANCH',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='employee_pg_education',
            name='PERCENTAGE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee_ug_education',
            name='BRANCH',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='employee_ug_education',
            name='PERCENTAGE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee_x_education',
            name='Maths_PERCENTAGE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee_x_education',
            name='PERCENTAGE',
            field=models.IntegerField(default=0),
        ),
    ]
