# Generated by Django 2.2.3 on 2019-09-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190902_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_intermediate_education',
            name='Completion_Date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee_intermediate_education',
            name='Start_Date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee_pg_education',
            name='Completion_Date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee_pg_education',
            name='Start_Date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee_ug_education',
            name='Completion_Date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee_ug_education',
            name='Start_Date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee_x_education',
            name='Completion_Date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee_x_education',
            name='Start_Date',
            field=models.IntegerField(default=0),
        ),
    ]
