# Generated by Django 2.2.3 on 2019-09-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190902_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YEAR', models.IntegerField(default=0)),
                ('MONTH', models.IntegerField(default=0)),
                ('OLD_EMPLOYEE', models.CharField(max_length=30)),
            ],
        ),
    ]
