# Generated by Django 2.2.3 on 2019-09-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_employee_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_experience',
            name='id',
        ),
        migrations.AddField(
            model_name='employee_experience',
            name='ID_NO',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
